apiVersion: v1
kind: ConfigMap
metadata: 
  name: postgres-config
  namespace: {{ .Values.namespace }}
data: 
  postgres-url: jdbc:postgresql://postgres-service.spring-boot.svc.cluster.local:5432/postgres
